### ISSUE TITLE
Problème migration module Export

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/gn_module_export#86]
Lorsqu'on migre un GeoNature comprenant le module Export, le script `migration.sh` de GeoNature échoue avec cette erreur:
```
Import module exports
 ... FileNotFoundError /home/geonat/www/geonature_wip-permission_v2.5.3/var/log/gn_export/cron.log
Traceback (most recent call last):
  File "/home/geonat/www/geonature_wip-permission_v2.5.3/backend/geonature/core/command/__init__.py", line 17, in import_cmd
    module_cms = __import__("{}.backend.commands.geonature_cmd".format(dir_name))
  File "/home/geonat/www/geonature_wip-permission_v2.5.3/external_modules/exports/backend/commands/geonature_cmd.py", line 14, in <module>
    str(ROOT_DIR / "var/log/gn_export/cron.log"), mode="w"
  File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/geonat/www/geonature_wip-permission_v2.5.3/var/log/gn_export/cron.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "geonature_cmd.py", line 31, in <module>
    import geonature.core.command  # pylint: disable=E0401,C0413
  File "/home/geonat/www/geonature_wip-permission_v2.5.3/backend/geonature/core/command/__init__.py", line 35, in <module>
    import_cmd(dir_name)
  File "/home/geonat/www/geonature_wip-permission_v2.5.3/backend/geonature/core/command/__init__.py", line 24, in import_cmd
    Path(os.path.dir_name(e.filename)).mkdir(parents=True, exist_ok=True)
AttributeError: module 'posixpath' has no attribute 'dir_name'
```

Il faudrait que le dossier `var/log/gn_export/` et le fichier `var/log/gn_export/cron.log` soit créé par le script `migration.sh` ou le module (?).

**Solution de contournement ("_workaround_")** : créer le dossier et le fichier manuellement ( `mkdir -p /home/${USER}/geonature/var/log/gn_export/ ; touch /home/${USER}/geonature/var/log/gn_export/cron.log` ) puis relancer le script `migration.sh`.

**Comment by amandine-sahl** [comment]
Le soucis est identifié et à été corrigé avec la 1.1.0 pour ce qui est du répertoire geonature/var/log/gn_export : https://github.com/PnX-SI/gn_module_export/releases/tag/1.1.0

`Si il n'existe pas déjà, créer le répertoire geonature/var/log/gn_export`

**Comment by camillemonchicourt** [comment]
Oui voir https://github.com/PnX-SI/gn_module_export/commit/fdb0b7a75ee78ba59888faeff439186e4a48a0ae

**Comment by jpm-cbna** [comment]
Ok, effectivement. Je n'avais pas fait attention que j'étais resté en version 1.0.0 sur notre serveur.
Merci pour le retour.
