### ISSUE TITLE
Erreur à l'installation sur une installation GeoNature fraiche (v2.5.5)

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/gn_module_export#90]
Lors de l'installation du module (v1.2.2) échoue sur une install fraiche de GeoNature (v2.5.5), avec le message suivant, a priori un problème pour trouver la config. Fonctionne avec une v1.2.1.

Commande lancée: `geonature install_gn_module /home/geonature/gn_modules/gn_module_export exports`

```
[...]
Checking file conformity
      install_gn_module  OK
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/geonature/geonature/backend/geonature/core/command/create_gn_module.py", line 80, in install_gn_module
    q = DB.session.query(TModules).filter(TModules.module_code == module_code).one()
  File "/home/geonature/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3473, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonature/geonature/backend/geonature/core/command/create_gn_module.py", line 97, in install_gn_module
    check_codefile_validity(module_path, module_code)
  File "/home/geonature/geonature/backend/geonature/utils/gn_module_import.py", line 226, in check_codefile_validity
    from backend.blueprint import blueprint
  File "/home/geonature/gn_modules/gn_module_export/backend/blueprint.py", line 539, in <module>
    if current_app.config.get("EXPORTS").get("expose_dsw_api"):
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonature/geonature/backend/geonature/core/command/create_gn_module.py", line 140, in install_gn_module
    "Error during module {} installation".format(module_code)
geonature.utils.errors.GeoNatureError: Error during module EXPORTS installation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonature/geonature/backend/venv/bin/geonature", line 3, in <module>
    geonature.core.command.main()
  File "/home/geonature/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonature/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/geonature/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonature/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonature/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/geonature/geonature/backend/geonature/core/command/create_gn_module.py", line 153, in install_gn_module
    if fresh_install:
UnboundLocalError: local variable 'fresh_install' referenced before assignment
```

**Comment by camillemonchicourt** [comment]
Ok en effet il y a une erreur dans le nommage du nouveau paramètre dans le fichier de conf par défaut (où il est nommé expose_api_sdw)

**Comment by camillemonchicourt** [comment]
La release 1.2.3 devrait corriger le soucis.

**Comment by lpofredc** [comment]
Le problème persiste et semble plus profond. En ajoutant le code suivant avant la ligne suivant, https://github.com/PnX-SI/gn_module_export/blob/76b904fdf330abd74d92c3a71d030c4db2b251f5/backend/blueprint.py#L539

```python3
try:
    print('current_app.config.get("EXPORTS")', current_app.config.get("EXPORTS").keys())
except:
    try:
        print('current_app.config["EXPORTS"]', current_app.config["EXPORTS"].keys())
    except:
        print('current_app.config.keys()', current_app.config.keys())
        print('ECHEC get config')

if current_app.config.get("EXPORTS").get("expose_dsw_api"):
    ...

```
On obtient le résultat suivant. La config du module ne semble pas se charger car les commandes  ̀`current_app.config.get("EXPORTS")` et `current_app.config["EXPORTS"]` échouent et `current_app.config` ne contient aucune clé `EXPORTS`.

```
Checking file conformity
      install_gn_module  OK
current_app.config.keys() dict_keys(['ENV', 'DEBUG', 'TESTING', 'PROPAGATE_EXCEPTIONS', 'PRESERVE_CONTEXT_ON_EXCEPTION', 'SECRET_KEY', 'PERMANENT_SESSION_LIFETIME', 'USE_X_SENDFILE', 'SERVER_NAME', 'APPLICATION_ROOT', 'SESSION_COOKIE_NAME', 'SESSION_COOKIE_DOMAIN', 'SESSION_COOKIE_PATH', 'SESSION_COOKIE_HTTPONLY', 'SESSION_COOKIE_SECURE', 'SESSION_COOKIE_SAMESITE', 'SESSION_REFRESH_EACH_REQUEST', 'MAX_CONTENT_LENGTH', 'SEND_FILE_MAX_AGE_DEFAULT', 'TRAP_BAD_REQUEST_ERRORS', 'TRAP_HTTP_EXCEPTIONS', 'EXPLAIN_TEMPLATE_LOADING', 'PREFERRED_URL_SCHEME', 'JSON_AS_ASCII', 'JSON_SORT_KEYS', 'JSONIFY_PRETTYPRINT_REGULAR', 'JSONIFY_MIMETYPE', 'TEMPLATES_AUTO_RELOAD', 'MAX_COOKIE_SIZE', 'MEDIAS', 'appName', 'DEFAULT_LANGUAGE', 'RIGHTS', 'SYNTHESE', 'LOCAL_SRID', 'UPLOAD_FOLDER', 'API_ENDPOINT', 'CAS_PUBLIC', 'PASS_METHOD', 'MAPCONFIG', 'URL_APPLICATION', 'MTD_API_ENDPOINT', 'GEONATURE_VERSION', 'ID_APPLICATION_GEONATURE', 'LOGO_STRUCTURE_FILE', 'ACCOUNT_MANAGEMENT', 'XML_NAMESPACE', 'ENABLE_NOMENCLATURE_TAXONOMIC_FILTERS', 'API_TAXHUB', 'FRONTEND', 'BDD', 'METADATA', 'COOKIE_EXPIRATION', 'TRAP_ALL_EXCEPTIONS', 'MAIL_ON_EECHEC get configRROR', 'CAS', 'SERVER', 'COOKIE_AUTORENEW', 'SQLALCHEMY_DATABASE_URI', 'MAIL_CONFIG', 'SESSION_TYPE', 'BASE_DIR', 'SQLALCHEMY_TRACK_MODIFICATIONS', 'SQLALCHEMY_BINDS', 'SQLALCHEMY_NATIVE_UNICODE', 'SQLALCHEMY_ECHO', 'SQLALCHEMY_RECORD_QUERIES', 'SQLALCHEMY_POOL_SIZE', 'SQLALCHEMY_POOL_TIMEOUT', 'SQLALCHEMY_POOL_RECYCLE', 'SQLALCHEMY_MAX_OVERFLOW', 'SQLALCHEMY_COMMIT_ON_TEARDOWN', 'DB', 'MA', 'ID_APP', 'after_USERSHUB_request', 'MAIL_SERVER', 'MAIL_MAX_EMAILS', 'MAIL_USE_SSL', 'ERROR_MAIL_TO', 'MAIL_USERNAME', 'MAIL_ASCII_ATTACHMENTS', 'MAIL_PORT', 'MAIL_USE_TLS', 'MAIL_DEFAULT_SENDER', 'MAIL_PASSWORD'])
ECHEC get config
```

Voici le log complet de l'erreur:
```
(venv) geonature@gna:~/gn_modules$ geonature install_gn_module /home/geonature/gn_modules/gn_module_export/ exports
Import module exports
 ... Module imported
checking file
...ok


checking manifest
...ok


NoResultFound No row was found for one()
>>> gn_module_import_requirements
import_requirements
Requirement already satisfied: rdflib==4.2.2 in /home/geonature/geonature/backend/venv/lib/python3.7/site-packages (from -r /home/geonature/gn_modules/gn_module_export/backend/requirements.txt (line 1)) (4.2.2)
Requirement already satisfied: python-crontab==2.4.0 in /home/geonature/geonature/backend/venv/lib/python3.7/site-packages (from -r /home/geonature/gn_modules/gn_module_export/backend/requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: python-dateutil in /home/geonature/geonature/backend/venv/lib/python3.7/site-packages (from python-crontab==2.4.0->-r /home/geonature/gn_modules/gn_module_export/backend/requirements.txt (line 2)) (2.6.1)
Requirement already satisfied: pyparsing in /home/geonature/geonature/backend/venv/lib/python3.7/site-packages (from rdflib==4.2.2->-r /home/geonature/gn_modules/gn_module_export/backend/requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: isodate in /home/geonature/geonature/backend/venv/lib/python3.7/site-packages (from rdflib==4.2.2->-r /home/geonature/gn_modules/gn_module_export/backend/requirements.txt (line 1)) (0.6.0)
Requirement already satisfied: six in /home/geonature/geonature/backend/venv/lib/python3.7/site-packages (from isodate->rdflib==4.2.2->-r /home/geonature/gn_modules/gn_module_export/backend/requirements.txt (line 1)) (1.11.0)
...ok


>>> check_codefile_validity
Checking file conformity
      install_gn_module  OK
current_app.config.keys() dict_keys(['ENV', 'DEBUG', 'TESTING', 'PROPAGATE_EXCEPTIONS', 'PRESERVE_CONTEXT_ON_EXCEPTION', 'SECRET_KEY', 'PERMANENT_SESSION_LIFETIME', 'USE_X_SENDFILE', 'SERVER_NAME', 'APPLICATION_ROOT', 'SESSION_COOKIE_NAME', 'SESSION_COOKIE_DOMAIN', 'SESSION_COOKIE_PATH', 'SESSION_COOKIE_HTTPONLY', 'SESSION_COOKIE_SECURE', 'SESSION_COOKIE_SAMESITE', 'SESSION_REFRESH_EACH_REQUEST', 'MAX_CONTENT_LENGTH', 'SEND_FILE_MAX_AGE_DEFAULT', 'TRAP_BAD_REQUEST_ERRORS', 'TRAP_HTTP_EXCEPTIONS', 'EXPLAIN_TEMPLATE_LOADING', 'PREFERRED_URL_SCHEME', 'JSON_AS_ASCII', 'JSON_SORT_KEYS', 'JSONIFY_PRETTYPRINT_REGULAR', 'JSONIFY_MIMETYPE', 'TEMPLATES_AUTO_RELOAD', 'MAX_COOKIE_SIZE', 'MEDIAS', 'appName', 'DEFAULT_LANGUAGE', 'RIGHTS', 'SYNTHESE', 'LOCAL_SRID', 'UPLOAD_FOLDER', 'API_ENDPOINT', 'CAS_PUBLIC', 'PASS_METHOD', 'MAPCONFIG', 'URL_APPLICATION', 'MTD_API_ENDPOINT', 'GEONATURE_VERSION', 'ID_APPLICATION_GEONATURE', 'LOGO_STRUCTURE_FILE', 'ACCOUNT_MANAGEMENT', 'XML_NAMESPACE', 'ENABLE_NOMENCLATURE_TAXONOMIC_FILTERS', 'API_TAXHUB', 'FRONTEND', 'BDD', 'METADATA', 'COOKIE_EXPIRATION', 'TRAP_ALL_EXCEPTIONS', 'MAIL_ON_ERROR', 'CAS', 'SERVER', 'COOKIE_AUTORENEW', 'SQLALCHEMY_DATABASE_URI', 'MAIL_CONFIG', 'SESSION_TYPE', 'BASE_DIR', 'SQLALCHEMY_TRACK_MODIFICATIONS', 'SQLALCHEMY_BINDS', 'SQLALCHEMY_NATIVE_UNICODE', 'SQLALCHEMY_ECHO', 'SQLALCHEMY_RECORD_QUERIES', 'SQLALCHEMY_POOL_SIZE', 'SQLALCHEMY_POOL_TIMEOUT', 'SQLALCHEMY_POOL_RECYCLE', 'SQLALCHEMY_MAX_OVERFLOW', 'SQLALCHEMY_COMMIT_ON_TEARDOWN', 'DB', 'MA', 'ID_APP', 'after_USERSHUB_request', 'MAIL_SERVER', 'MAIL_MAX_EMAILS', 'MAIL_USE_SSL', 'ERROR_MAIL_TO', 'MAIL_USERNAME', 'MAIL_ASCII_ATTACHMENTS', 'MAIL_PORT', 'MAIL_USE_TLS', 'MAIL_DEFAULT_SENDER', 'MAIL_PASSWORD'])
ECHEC get config
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/geonature/geonature/backend/geonature/core/command/create_gn_module.py", line 80, in install_gn_module
    q = DB.session.query(TModules).filter(TModules.module_code == module_code).one()
  File "/home/geonature/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3473, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonature/geonature/backend/geonature/core/command/create_gn_module.py", line 97, in install_gn_module
    check_codefile_validity(module_path, module_code)
  File "/home/geonature/geonature/backend/geonature/utils/gn_module_import.py", line 226, in check_codefile_validity
    from backend.blueprint import blueprint
  File "/home/geonature/gn_modules/gn_module_export/backend/blueprint.py", line 547, in <module>
    if current_app.config.get("EXPORTS").get("expose_dsw_api"):
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonature/geonature/backend/geonature/core/command/create_gn_module.py", line 140, in install_gn_module
    "Error during module {} installation".format(module_code)
geonature.utils.errors.GeoNatureError: Error during module EXPORTS installation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonature/geonature/backend/venv/bin/geonature", line 3, in <module>
    geonature.core.command.main()
  File "/home/geonature/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonature/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/geonature/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonature/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonature/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/geonature/geonature/backend/geonature/core/command/create_gn_module.py", line 153, in install_gn_module
    if fresh_install:
UnboundLocalError: local variable 'fresh_install' referenced before assignment
```

**Comment by camillemonchicourt** [comment]
OK alors là ça dépasse la compréhension.
Pourtant je vois pas ce qu'il y a de nouveau dans la 1.2.2 qui a pu entraîné cela. 🤔

**Comment by camillemonchicourt** [comment]
Corrigé dans la 1.2.4
